version: "3.7"
services:
  frontend:
    image: node:lts-alpine
    command: sh -c "yarn serve"
    ports:
      - 8081:8080
    working_dir: /app
    volumes:
      - ./front:/app
  backend:
    image: cosmtrek/air
    command: air
    working_dir: /back
    volumes:
      - ./back:/back
    ports:
      - 8080:80
  db:
    image: cassandra:latest
    
